[SourceKitStressTester] Add setting to limit sk-swiftc-wrapper's stderr/stdout output to that of the compiler
This stops the wrapper from reporting progress/results inline, which was causing
SwiftPM to fail the invocation with:
> error: failed parsing the Swift compiler output:  invalid message size
as it was passing -parseable-output the sk-swiftc-wrapper (which is treated as
swiftc) and the extra progress output the wrapper produces isn't parseable.